ip = "95.216.143.121"
port = 5000
cwd = "./data"

# Make sure that routes with '*' come last
[routes.resources]
methods = ["GET"]
url = "/r/*"
path = "resources/*"

[routes.style]
methods = ["GET"]
url = "/s/style.css"
path = "style.css"
content_type = "text/css"

[routes.index]
methods = ["GET"]
url = "/"
path = "index.html"
content_type = "text/html"

[routes.main]
methods = ["GET"]
url = "/a/*"
path = "*.html"
content_type = "text/html"
